version: "3.8"

services:
  db:
    image: postgres:16-alpine
    container_name: reserva-de-mesas-postgres
    environment:
      POSTGRES_DB: reserva_de_mesas
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d reserva_de_mesas"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: api-reserva-de-mesas
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/reserva_de_mesas
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    ports:
      - "8080:8080"
volumes:
  db_data:
